### ISSUE TITLE
Can't create Audio frame with from_ndarray

### ISSUE THREAD

**Issue by IsmaelDeveloper** [PyAV-Org/PyAV#1236]
I'm trying to use PyAV for create an audio frame and I have an error I can't fix since days now. This is my custom audio class:
```python
  class CustomAudioTrack(MediaStreamTrack):
      kind = "audio"
  
      def __init__(self, rate=48000, channels=2):
          super().__init__()
          self.rate = rate
          self.channels = channels
          self._timestamp = 0
  
      async def recv(self):
          # number of frame to read 
          frames = int(self.rate / 10)
          data = sd.rec(frames, samplerate=self.rate,
                        channels=self.channels, dtype=np.int16)
          sd.wait()  
  
          # timestamp update
          self._timestamp += frames
          pts = self._timestamp
          time_base = fractions.Fraction(1, self.rate)
  
          # audio frame creation
          audio_frame = av.AudioFrame.from_ndarray(
              data, format='s16', layout='stereo')
          audio_frame.sample_rate = self.rate
          audio_frame.pts = pts
          audio_frame.time_base = time_base
  
          return audio_frame

```
         
My error is:
```
Traceback (most recent call last):
  File "C:\Users\poppppp\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiortc\rtcrtpsender.py", line 328, in _run_rtp
    enc_frame = await self._next_encoded_frame(codec)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\poppppp\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiortc\rtcrtpsender.py", line 270, in _next_encoded_frame
    data = await self.__track.recv()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\documents\project\pythonProject\webrtc_tutorial\sadda_python\offerer.py", line 44, in recv
    audio_frame = av.AudioFrame.from_ndarray(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "av\\audio\\frame.pyx", line 125, in av.audio.frame.AudioFrame.from_ndarray
  File "av\\utils.pyx", line 79, in av.utils.check_ndarray_shape
ValueError: Unexpected numpy array shape `(4800, 2)`
```

Do you have any idea how I can fix this? Thank you very much!

**Comment by IsmaelDeveloper** [comment]
actually It work perfectly if I have only one channel but I dont choose and my microphone is a stereo one so I have to use it witch 2 channel. And I dont understand why the numpy array doesnt work.

**Comment by WyattBlue** [comment]
The exception is triggering because your audio format isn't planar.

```python
        if AudioFormat(format).is_planar:
            ...
        else:
            check_ndarray_shape(array, array.shape[0] == 1)
            samples = array.shape[1] // nb_channels
```

You should just be able to reshape your numpy array so that is just one dimension. The audio frame will still be stereo.

**Comment by IsmaelDeveloper** [comment]
Thank you for your quick answer ! But im not sure to understand how to use it in my example.. Thanks for your help again

**Comment by IsmaelDeveloper** [comment]
actually with something like that : 
`class CustomAudioTrack(MediaStreamTrack):
    kind = "audio"

    def __init__(self, rate=48000, channels=2):
        super().__init__()
        self.rate = rate
        self.channels = channels
        self._timestamp = 0

    async def recv(self):
        frames_per_buffer = int(self.rate * 0.1)
        data = sd.rec(frames_per_buffer, samplerate=self.rate,
                      channels=self.channels, dtype=np.int16)
        sd.wait()
        self._timestamp += frames_per_buffer
        pts = self._timestamp
        time_base = fractions.Fraction(1, self.rate)
        data_interleaved = np.ravel(data, order='C').reshape(-1, 2)
        # Création de la trame audio
        audio_frame = av.AudioFrame.from_ndarray(
            data_interleaved.T, format='s16', layout='stereo')
        audio_frame.sample_rate = self.rate
        audio_frame.pts = pts
        audio_frame.time_base = time_base

        return audio_frame`

i redimension my numpy array but then got this error : 
ValueError: Expected numpy array with ndim `2` but got `1`

**Comment by IsmaelDeveloper** [comment]
if someone has just a little mini idea of the solution i would appreciate ! Thanks for help :)

**Comment by IsmaelDeveloper** [comment]
I made the test and thats what i have without reshape anaything : 
data :  [[ 0  0]
 [-1  0]
 [ 0  0]
 ...
 [ 0  0]
 [ 0 -1]
 [ 0  0]]
shape :  (4800, 2)

what format of data and shape does  av.AudioFrame.from_ndarray need for stereo please ?

**Comment by IsmaelDeveloper** [comment]
I think I found a solution but I want to be sure about something. I remade the code like that and I dont have any error anymore. the problem is that when I read my sound, it doesnt work well at all. I wonder if my audio stay in stereo with this code : 

```
class CustomAudioTrack(MediaStreamTrack):
    kind = "audio"

    def __init__(self, rate=48000, channels=2):
        super().__init__()
        self.rate = rate
        self.channels = channels
        self._timestamp = 0

    async def recv(self):
        frames_per_buffer = int(self.rate * 0.1)
        data = sd.rec(frames_per_buffer, samplerate=self.rate,
                      channels=self.channels, dtype=np.int16)
        sd.wait()
        self._timestamp += frames_per_buffer
        pts = self._timestamp
        time_base = fractions.Fraction(1, self.rate)
        # Création de la trame audio
        data_flattened = np.ravel(data, order='C').reshape(-1, 1)

        print("data : ", data_flattened)
        print("shape : ", data.shape)
        audio_frame = av.AudioFrame.from_ndarray(
            data_flattened.T, format='s16', layout='stereo')
        audio_frame.sample_rate = self.rate
        audio_frame.pts = pts
        audio_frame.time_base = time_base

        return audio_frame
```

**Comment by IsmaelDeveloper** [comment]
I will close the topic with the final custom class : 

```
class CustomAudioTrack(MediaStreamTrack):
    kind = "audio"

    def __init__(self, rate=48000, channels=2):
        super().__init__()
        self.rate = rate
        self.channels = channels
        self._timestamp = 0

        # Initialiser PyAudio
        self.pa = pyaudio.PyAudio()
        self.stream = self.pa.open(format=pyaudio.paInt16,
                                   channels=2,
                                   rate=48000,
                                   input=True,
                                   frames_per_buffer=960)

    async def recv(self):
        frames_per_buffer = 960

        # Lire les données du stream PyAudio
        data = np.frombuffer(self.stream.read(
            frames_per_buffer), dtype=np.int16)
        data = data.reshape(-1, 1)

        self._timestamp += frames_per_buffer
        pts = self._timestamp
        time_base = Fraction(1, self.rate)
        # Préparation des données pour PyAV
        audio_frame = av.AudioFrame.from_ndarray(
            data.T, format='s16', layout='stereo')
        audio_frame.sample_rate = self.rate
        audio_frame.pts = pts
        audio_frame.time_base = time_base

        return audio_frame

    def __del__(self):
        self.stream.stop_stream()
        self.stream.close()
        self.pa.terminate()
```
