### ISSUE TITLE
Setup.py is broken when using Cython 3.0a6

### ISSUE THREAD

**Issue by yudonglin** [PyAV-Org/PyAV#727]
In setup.py, line 36: 
`if tuple(map(int, cython_version.split('.'))) < (0, 27):`
However, if people are using Cython 3.0a6, this does not work because the version part will be a string instead of an integer...
```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Administrator\AppData\Local\Temp\pip-install-jkvm3_sm\av_fab2624fe83a41c19d0e4cd1612d76bb\setup.py", line 36, in <module>
        if tuple(map(int, cython_version.split('.'))) < (0, 27):
    ValueError: invalid literal for int() with base 10: '0a6'
```
My suggestion is... using the try function first, then check the version in string type.

**Comment by yudonglin** [comment]
#712 I think this may fix it...
