### ISSUE TITLE
undefined symbol:av_muxer_iterate

### ISSUE THREAD

**Issue by lishiyuhebei** [PyAV-Org/PyAV#739]
## Overview

when i run "import av " in python3.6 .I got "ImportError: /home/sidney/source_dir/pyav/PyAV/av/format.cpython-36m-x86_64-linux-gnu.so: undefined symbol: av_muxer_iterate"

## Expected behavior

I want to use pyav to analysis of h264 bit stream.

## Actual behavior

when i run "import av " in python3.6 .I got "ImportError: /home/sidney/source_dir/pyav/PyAV/av/format.cpython-36m-x86_64-linux-gnu.so: undefined symbol: av_muxer_iterate"

Build report:
```
method 1:
(Linux.5.4.0-65-generic.cpython3.6) sidney@sidney-HP:~/source_dir/pyav/PyAV$  pip install av
Requirement already satisfied: av in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (8.0.3)

method 2:
(Linux.5.4.0-65-generic.cpython3.6) sidney@sidney-HP:~/source_dir/pyav/PyAV$ source scripts/activate.sh

(Linux.5.4.0-65-generic.cpython3.6) sidney@sidney-HP:~/source_dir/pyav/PyAV$ pip install --upgrade -r tests/requirements.txt
Requirement already satisfied: autopep8 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from -r tests/requirements.txt (line 1)) (1.5.4)
Requirement already satisfied: Cython in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from -r tests/requirements.txt (line 2)) (0.29.21)
Requirement already satisfied: editorconfig in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from -r tests/requirements.txt (line 3)) (0.12.3)
Requirement already satisfied: flake8 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from -r tests/requirements.txt (line 4)) (3.8.4)
Requirement already satisfied: isort in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from -r tests/requirements.txt (line 5)) (5.7.0)
Requirement already satisfied: numpy in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from -r tests/requirements.txt (line 6)) (1.19.5)
Requirement already satisfied: Pillow in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from -r tests/requirements.txt (line 7)) (8.1.0)
Requirement already satisfied: sphinx in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from -r tests/requirements.txt (line 8)) (3.4.3)
Requirement already satisfied: pycodestyle>=2.6.0 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from autopep8->-r tests/requirements.txt (line 1)) (2.6.0)
Requirement already satisfied: toml in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from autopep8->-r tests/requirements.txt (line 1)) (0.10.2)
Requirement already satisfied: importlib-metadata in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from flake8->-r tests/requirements.txt (line 4)) (3.4.0)
Requirement already satisfied: pyflakes<2.3.0,>=2.2.0 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from flake8->-r tests/requirements.txt (line 4)) (2.2.0)
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from flake8->-r tests/requirements.txt (line 4)) (0.6.1)
Requirement already satisfied: babel>=1.3 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from sphinx->-r tests/requirements.txt (line 8)) (2.9.0)
Requirement already satisfied: setuptools in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from sphinx->-r tests/requirements.txt (line 8)) (53.0.0)
Requirement already satisfied: docutils>=0.12 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from sphinx->-r tests/requirements.txt (line 8)) (0.16)
Requirement already satisfied: Jinja2>=2.3 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from sphinx->-r tests/requirements.txt (line 8)) (2.11.3)
Requirement already satisfied: Pygments>=2.0 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from sphinx->-r tests/requirements.txt (line 8)) (2.7.4)
Requirement already satisfied: imagesize in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from sphinx->-r tests/requirements.txt (line 8)) (1.2.0)
Requirement already satisfied: sphinxcontrib-applehelp in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from sphinx->-r tests/requirements.txt (line 8)) (1.0.2)
Requirement already satisfied: sphinxcontrib-jsmath in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from sphinx->-r tests/requirements.txt (line 8)) (1.0.1)
Requirement already satisfied: sphinxcontrib-devhelp in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from sphinx->-r tests/requirements.txt (line 8)) (1.0.2)
Requirement already satisfied: sphinxcontrib-serializinghtml in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from sphinx->-r tests/requirements.txt (line 8)) (1.1.4)
Requirement already satisfied: sphinxcontrib-qthelp in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from sphinx->-r tests/requirements.txt (line 8)) (1.0.3)
Requirement already satisfied: snowballstemmer>=1.1 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from sphinx->-r tests/requirements.txt (line 8)) (2.1.0)
Requirement already satisfied: packaging in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from sphinx->-r tests/requirements.txt (line 8)) (20.9)
Requirement already satisfied: alabaster<0.8,>=0.7 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from sphinx->-r tests/requirements.txt (line 8)) (0.7.12)
Requirement already satisfied: requests>=2.5.0 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from sphinx->-r tests/requirements.txt (line 8)) (2.25.1)
Requirement already satisfied: sphinxcontrib-htmlhelp in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from sphinx->-r tests/requirements.txt (line 8)) (1.0.3)
Requirement already satisfied: pytz>=2015.7 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from babel>=1.3->sphinx->-r tests/requirements.txt (line 8)) (2021.1)
Requirement already satisfied: MarkupSafe>=0.23 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from Jinja2>=2.3->sphinx->-r tests/requirements.txt (line 8)) (1.1.1)
Requirement already satisfied: chardet<5,>=3.0.2 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from requests>=2.5.0->sphinx->-r tests/requirements.txt (line 8)) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from requests>=2.5.0->sphinx->-r tests/requirements.txt (line 8)) (1.26.3)
Requirement already satisfied: idna<3,>=2.5 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from requests>=2.5.0->sphinx->-r tests/requirements.txt (line 8)) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from requests>=2.5.0->sphinx->-r tests/requirements.txt (line 8)) (2020.12.5)
Requirement already satisfied: typing-extensions>=3.6.4 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from importlib-metadata->flake8->-r tests/requirements.txt (line 4)) (3.7.4.3)
Requirement already satisfied: zipp>=0.5 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from importlib-metadata->flake8->-r tests/requirements.txt (line 4)) (3.4.0)
Requirement already satisfied: pyparsing>=2.0.2 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from packaging->sphinx->-r tests/requirements.txt (line 8)) (2.4.7)

(Linux.5.4.0-65-generic.cpython3.6) sidney@sidney-HP:~/source_dir/pyav/PyAV$ ./scripts/build-deps
Requirement already satisfied: autopep8 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from -r tests/requirements.txt (line 1)) (1.5.4)
Requirement already satisfied: Cython in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from -r tests/requirements.txt (line 2)) (0.29.21)
Requirement already satisfied: editorconfig in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from -r tests/requirements.txt (line 3)) (0.12.3)
Requirement already satisfied: flake8 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from -r tests/requirements.txt (line 4)) (3.8.4)
Requirement already satisfied: isort in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from -r tests/requirements.txt (line 5)) (5.7.0)
Requirement already satisfied: numpy in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from -r tests/requirements.txt (line 6)) (1.19.5)
Requirement already satisfied: Pillow in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from -r tests/requirements.txt (line 7)) (8.1.0)
Requirement already satisfied: sphinx in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from -r tests/requirements.txt (line 8)) (3.4.3)
Requirement already satisfied: pycodestyle>=2.6.0 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from autopep8->-r tests/requirements.txt (line 1)) (2.6.0)
Requirement already satisfied: toml in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from autopep8->-r tests/requirements.txt (line 1)) (0.10.2)
Requirement already satisfied: pyflakes<2.3.0,>=2.2.0 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from flake8->-r tests/requirements.txt (line 4)) (2.2.0)
Requirement already satisfied: importlib-metadata in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from flake8->-r tests/requirements.txt (line 4)) (3.4.0)
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from flake8->-r tests/requirements.txt (line 4)) (0.6.1)
Requirement already satisfied: alabaster<0.8,>=0.7 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from sphinx->-r tests/requirements.txt (line 8)) (0.7.12)
Requirement already satisfied: imagesize in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from sphinx->-r tests/requirements.txt (line 8)) (1.2.0)
Requirement already satisfied: sphinxcontrib-serializinghtml in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from sphinx->-r tests/requirements.txt (line 8)) (1.1.4)
Requirement already satisfied: Pygments>=2.0 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from sphinx->-r tests/requirements.txt (line 8)) (2.7.4)
Requirement already satisfied: sphinxcontrib-jsmath in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from sphinx->-r tests/requirements.txt (line 8)) (1.0.1)
Requirement already satisfied: sphinxcontrib-applehelp in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from sphinx->-r tests/requirements.txt (line 8)) (1.0.2)
Requirement already satisfied: docutils>=0.12 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from sphinx->-r tests/requirements.txt (line 8)) (0.16)
Requirement already satisfied: Jinja2>=2.3 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from sphinx->-r tests/requirements.txt (line 8)) (2.11.3)
Requirement already satisfied: sphinxcontrib-qthelp in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from sphinx->-r tests/requirements.txt (line 8)) (1.0.3)
Requirement already satisfied: snowballstemmer>=1.1 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from sphinx->-r tests/requirements.txt (line 8)) (2.1.0)
Requirement already satisfied: babel>=1.3 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from sphinx->-r tests/requirements.txt (line 8)) (2.9.0)
Requirement already satisfied: packaging in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from sphinx->-r tests/requirements.txt (line 8)) (20.9)
Requirement already satisfied: requests>=2.5.0 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from sphinx->-r tests/requirements.txt (line 8)) (2.25.1)
Requirement already satisfied: setuptools in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from sphinx->-r tests/requirements.txt (line 8)) (53.0.0)
Requirement already satisfied: sphinxcontrib-htmlhelp in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from sphinx->-r tests/requirements.txt (line 8)) (1.0.3)
Requirement already satisfied: sphinxcontrib-devhelp in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from sphinx->-r tests/requirements.txt (line 8)) (1.0.2)
Requirement already satisfied: pytz>=2015.7 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from babel>=1.3->sphinx->-r tests/requirements.txt (line 8)) (2021.1)
Requirement already satisfied: MarkupSafe>=0.23 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from Jinja2>=2.3->sphinx->-r tests/requirements.txt (line 8)) (1.1.1)
Requirement already satisfied: certifi>=2017.4.17 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from requests>=2.5.0->sphinx->-r tests/requirements.txt (line 8)) (2020.12.5)
Requirement already satisfied: chardet<5,>=3.0.2 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from requests>=2.5.0->sphinx->-r tests/requirements.txt (line 8)) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from requests>=2.5.0->sphinx->-r tests/requirements.txt (line 8)) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from requests>=2.5.0->sphinx->-r tests/requirements.txt (line 8)) (1.26.3)
Requirement already satisfied: zipp>=0.5 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from importlib-metadata->flake8->-r tests/requirements.txt (line 4)) (3.4.0)
Requirement already satisfied: typing-extensions>=3.6.4 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from importlib-metadata->flake8->-r tests/requirements.txt (line 4)) (3.7.4.3)
Requirement already satisfied: pyparsing>=2.0.2 in ./venvs/Linux.5.4.0-65-generic.cpython3.6/lib/python3.6/site-packages (from packaging->sphinx->-r tests/requirements.txt (line 8)) (2.4.7)
We have a cached build of ffmpeg-4.2; skipping re-build.

(Linux.5.4.0-65-generic.cpython3.6) sidney@sidney-HP:~/source_dir/pyav/PyAV$ make
CFLAGS="-O0" LDFLAGS="" python3 setup.py build_ext --inplace --debug
running build_ext
running config
Warning: We don't understand some of CFLAGS (and will leave it in the envvar): -O0
PyAV: 8.0.4.dev0 v8.0.3-1-g2b40d57
Python: 3.6.9 (default, Oct  8 2020, 12:12:24) \n[GCC 8.4.0]
platform: Linux-5.4.0-65-generic-x86_64-with-Ubuntu-18.04-bionic
extension_extra:
	include_dirs: [b'include', b'/home/sidney/source_dir/pyav/PyAV/vendor/build/ffmpeg-4.2/include']
	libraries: [b'avformat', b'avcodec', b'avdevice', b'avutil', b'avfilter', b'swscale', b'swresample']
	library_dirs: [b'/home/sidney/source_dir/pyav/PyAV/vendor/build/ffmpeg-4.2/lib']
	define_macros: []
	runtime_library_dirs: []
config_macros:
	PYAV_COMMIT_STR="v8.0.3-1-g2b40d57"
	PYAV_VERSION=8.0.4.dev0
	PYAV_VERSION_STR="8.0.4.dev0"
writing build/temp.linux-x86_64-3.6/include/pyav/config.h
running cythonize
copying build/lib.linux-x86_64-3.6/av/_core.cpython-36m-x86_64-linux-gnu.so -> av
copying build/lib.linux-x86_64-3.6/av/packet.cpython-36m-x86_64-linux-gnu.so -> av
copying build/lib.linux-x86_64-3.6/av/buffer.cpython-36m-x86_64-linux-gnu.so -> av
copying build/lib.linux-x86_64-3.6/av/stream.cpython-36m-x86_64-linux-gnu.so -> av
copying build/lib.linux-x86_64-3.6/av/logging.cpython-36m-x86_64-linux-gnu.so -> av
copying build/lib.linux-x86_64-3.6/av/option.cpython-36m-x86_64-linux-gnu.so -> av
copying build/lib.linux-x86_64-3.6/av/plane.cpython-36m-x86_64-linux-gnu.so -> av
copying build/lib.linux-x86_64-3.6/av/bytesource.cpython-36m-x86_64-linux-gnu.so -> av
copying build/lib.linux-x86_64-3.6/av/frame.cpython-36m-x86_64-linux-gnu.so -> av
copying build/lib.linux-x86_64-3.6/av/utils.cpython-36m-x86_64-linux-gnu.so -> av
copying build/lib.linux-x86_64-3.6/av/enum.cpython-36m-x86_64-linux-gnu.so -> av
copying build/lib.linux-x86_64-3.6/av/descriptor.cpython-36m-x86_64-linux-gnu.so -> av
copying build/lib.linux-x86_64-3.6/av/error.cpython-36m-x86_64-linux-gnu.so -> av
copying build/lib.linux-x86_64-3.6/av/dictionary.cpython-36m-x86_64-linux-gnu.so -> av
copying build/lib.linux-x86_64-3.6/av/format.cpython-36m-x86_64-linux-gnu.so -> av
copying build/lib.linux-x86_64-3.6/av/codec/codec.cpython-36m-x86_64-linux-gnu.so -> av/codec
copying build/lib.linux-x86_64-3.6/av/codec/context.cpython-36m-x86_64-linux-gnu.so -> av/codec
copying build/lib.linux-x86_64-3.6/av/video/stream.cpython-36m-x86_64-linux-gnu.so -> av/video
copying build/lib.linux-x86_64-3.6/av/video/reformatter.cpython-36m-x86_64-linux-gnu.so -> av/video
copying build/lib.linux-x86_64-3.6/av/video/plane.cpython-36m-x86_64-linux-gnu.so -> av/video
copying build/lib.linux-x86_64-3.6/av/video/frame.cpython-36m-x86_64-linux-gnu.so -> av/video
copying build/lib.linux-x86_64-3.6/av/video/codeccontext.cpython-36m-x86_64-linux-gnu.so -> av/video
copying build/lib.linux-x86_64-3.6/av/video/format.cpython-36m-x86_64-linux-gnu.so -> av/video
copying build/lib.linux-x86_64-3.6/av/sidedata/sidedata.cpython-36m-x86_64-linux-gnu.so -> av/sidedata
copying build/lib.linux-x86_64-3.6/av/sidedata/motionvectors.cpython-36m-x86_64-linux-gnu.so -> av/sidedata
copying build/lib.linux-x86_64-3.6/av/audio/fifo.cpython-36m-x86_64-linux-gnu.so -> av/audio
copying build/lib.linux-x86_64-3.6/av/audio/stream.cpython-36m-x86_64-linux-gnu.so -> av/audio
copying build/lib.linux-x86_64-3.6/av/audio/plane.cpython-36m-x86_64-linux-gnu.so -> av/audio
copying build/lib.linux-x86_64-3.6/av/audio/frame.cpython-36m-x86_64-linux-gnu.so -> av/audio
copying build/lib.linux-x86_64-3.6/av/audio/layout.cpython-36m-x86_64-linux-gnu.so -> av/audio
copying build/lib.linux-x86_64-3.6/av/audio/codeccontext.cpython-36m-x86_64-linux-gnu.so -> av/audio
copying build/lib.linux-x86_64-3.6/av/audio/resampler.cpython-36m-x86_64-linux-gnu.so -> av/audio
copying build/lib.linux-x86_64-3.6/av/audio/format.cpython-36m-x86_64-linux-gnu.so -> av/audio
copying build/lib.linux-x86_64-3.6/av/subtitles/stream.cpython-36m-x86_64-linux-gnu.so -> av/subtitles
copying build/lib.linux-x86_64-3.6/av/subtitles/subtitle.cpython-36m-x86_64-linux-gnu.so -> av/subtitles
copying build/lib.linux-x86_64-3.6/av/subtitles/codeccontext.cpython-36m-x86_64-linux-gnu.so -> av/subtitles
copying build/lib.linux-x86_64-3.6/av/filter/pad.cpython-36m-x86_64-linux-gnu.so -> av/filter
copying build/lib.linux-x86_64-3.6/av/filter/link.cpython-36m-x86_64-linux-gnu.so -> av/filter
copying build/lib.linux-x86_64-3.6/av/filter/filter.cpython-36m-x86_64-linux-gnu.so -> av/filter
copying build/lib.linux-x86_64-3.6/av/filter/graph.cpython-36m-x86_64-linux-gnu.so -> av/filter
copying build/lib.linux-x86_64-3.6/av/filter/context.cpython-36m-x86_64-linux-gnu.so -> av/filter
copying build/lib.linux-x86_64-3.6/av/container/core.cpython-36m-x86_64-linux-gnu.so -> av/container
copying build/lib.linux-x86_64-3.6/av/container/streams.cpython-36m-x86_64-linux-gnu.so -> av/container
copying build/lib.linux-x86_64-3.6/av/container/pyio.cpython-36m-x86_64-linux-gnu.so -> av/container
copying build/lib.linux-x86_64-3.6/av/container/output.cpython-36m-x86_64-linux-gnu.so -> av/container
copying build/lib.linux-x86_64-3.6/av/container/input.cpython-36m-x86_64-linux-gnu.so -> av/container
copying build/lib.linux-x86_64-3.6/av/data/stream.cpython-36m-x86_64-linux-gnu.so -> av/data
(Linux.5.4.0-65-generic.cpython3.6) sidney@sidney-HP:~/source_dir/pyav/PyAV$ 

```

## Investigation

 I had install av by "pip3 install av",but it does not work
I had install ffmpeg .

## Reproduction

(Linux.5.4.0-65-generic.cpython3.6) sidney@sidney-HP:~/source_dir/pyav/PyAV$  ffmpeg

ffmpeg version 4.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --disable-doc --disable-mmx --disable-optimizations --disable-static --disable-stripping --enable-debug=3 --enable-gpl --enable-libx264 --enable-shared --prefix=/home/sidney/source_dir/pyav/PyAV/vendor/build/ffmpeg-4.2
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'

## Versions

- OS:  uname -a
Linux sidney-HP 5.4.0-65-generic #73~18.04.1-Ubuntu SMP Tue Jan 19 09:02:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- PyAV runtime:
```
(Linux.5.4.0-65-generic.cpython3.6) sidney@sidney-HP:~/source_dir/pyav/PyAV$ python -m av --version
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/sidney/source_dir/pyav/PyAV/av/__init__.py", line 15, in <module>
    from av.audio.fifo import AudioFifo
  File "/home/sidney/source_dir/pyav/PyAV/av/audio/__init__.py", line 1, in <module>
    from .frame import AudioFrame
  File "av/audio/frame.pyx", line 1, in init av.audio.frame
    from av.audio.format cimport get_audio_format
  File "av/frame.pyx", line 1, in init av.frame
    from av.utils cimport avrational_to_fraction, to_avrational
  File "/home/sidney/source_dir/pyav/PyAV/av/codec/__init__.py", line 1, in <module>
    from .codec import (
  File "av/codec/codec.pyx", line 1, in init av.codec.codec
    from av.audio.format cimport get_audio_format
  File "/home/sidney/source_dir/pyav/PyAV/av/video/__init__.py", line 1, in <module>
    from .frame import VideoFrame
  File "av/video/frame.pyx", line 1, in init av.video.frame
    from libc.stdint cimport uint8_t
  File "av/codec/context.pyx", line 1, in init av.codec.context
    from libc.errno cimport EAGAIN
  File "/home/sidney/source_dir/pyav/PyAV/av/container/__init__.py", line 1, in <module>
    from .core import Container, Flags, open
  File "av/container/core.pyx", line 1, in init av.container.core
    from cython.operator cimport dereference
  File "av/packet.pyx", line 1, in init av.packet
    cimport libav as lib
  File "av/sidedata/sidedata.pyx", line 1, in init av.sidedata.sidedata
    from av.enum cimport define_enum
  File "av/container/streams.pyx", line 2, in init av.container.streams
    cimport libav as lib
ImportError: /home/sidney/source_dir/pyav/PyAV/av/format.cpython-36m-x86_64-linux-gnu.so: undefined symbol: av_muxer_iterate

```
- PyAV build:
```
(Linux.5.4.0-65-generic.cpython3.6) sidney@sidney-HP:~/source_dir/pyav/PyAV$ python setup.py config --verbose
running config
PyAV: 8.0.4.dev0 v8.0.3-1-g2b40d57
Python: 3.6.9 (default, Oct  8 2020, 12:12:24) \n[GCC 8.4.0]
platform: Linux-5.4.0-65-generic-x86_64-with-Ubuntu-18.04-bionic
extension_extra:
	include_dirs: [b'include', b'/home/sidney/source_dir/pyav/PyAV/vendor/build/ffmpeg-4.2/include']
	libraries: [b'avformat', b'avcodec', b'avdevice', b'avutil', b'avfilter', b'swscale', b'swresample']
	library_dirs: [b'/home/sidney/source_dir/pyav/PyAV/vendor/build/ffmpeg-4.2/lib']
	define_macros: []
	runtime_library_dirs: []
config_macros:
	PYAV_COMMIT_STR="v8.0.3-1-g2b40d57"
	PYAV_VERSION=8.0.4.dev0
	PYAV_VERSION_STR="8.0.4.dev0"
```
- FFmpeg:
```
(Linux.5.4.0-65-generic.cpython3.6) sidney@sidney-HP:~/source_dir/pyav/PyAV$ ffmpeg -version
ffmpeg version 4.2 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
configuration: --disable-doc --disable-mmx --disable-optimizations --disable-static --disable-stripping --enable-debug=3 --enable-gpl --enable-libx264 --enable-shared --prefix=/home/sidney/source_dir/pyav/PyAV/vendor/build/ffmpeg-4.2
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100
```

## Research

I have done the following:

- [ ] Looked through [old GitHub issues](https://github.com/PyAV-Org/PyAV/issues?&q=is%3Aissue)
- [ ] ... and waited 72 hours for a response.

## Additional context

Could you help me ?

**Comment by jlaine** [comment]
You are trying to run PyAV against an old FFmpeg version (not the 4.2 you built against). You will need to clean up your library search path.

Alternatively, just update your pip version and you should be able to get pre-built wheels for PyAV.
