### ISSUE TITLE
Getting av.error.FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by jsenpra** [PyAV-Org/PyAV#797]
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/acvs-tycoai-core-engine/facenet_master/tycoai_vision/visualize.py", line 298, in video_saver_pyav
    container.mux(packet)
  File "av/container/output.pyx", line 204, in av.container.output.OutputContainer.mux
  File "av/container/output.pyx", line 210, in av.container.output.OutputContainer.mux_one
  File "av/container/output.pyx", line 169, in av.container.output.OutputContainer.start_encoding
  File "av/error.pyx", line 336, in av.error.err_check
av.error.FileNotFoundError: [Errno 2] No such file or directory

System -- Ubuntu 18.0.4

Tried installing ffmpeg and av both from source as well as apt-get and pip3

**Comment by jlaine** [comment]
No idea what you're doing here, or how you hope anyone can help.
