### ISSUE TITLE
ImportError: DLL load failed while importing _core: The specified procedure could not be found.

### ISSUE THREAD

**Issue by JustinDBruce** [PyAV-Org/PyAV#811]
Hopefully I am in the right place. I am trying to build a python program with pyinstaller. When I run "python main.py" the program runs fine, but when I make an exe with pyinstaller I get the following error:
Traceback (most recent call last):
  File "main.py", line 8, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "scrcpy\__init__.py", line 6, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "scrcpy\core.py", line 12, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "av\__init__.py", line 9, in <module>
ImportError: DLL load failed while importing _core: The specified procedure could not be found.
[9264] Failed to execute script 'main' due to unhandled exception!

*If this helps my ide is showing that it cannot find the declaration to go to on CodecContext:
from av.codec import CodecContext

From what I have read I needed to make sure the the ffmpeg bin was added to the path, but I am still getting the same error. Any help on this would be great! Thanks!

**Comment by jlaine** [comment]
I'm sorry, this feels really out of scope for the project. Given our limited resources I'm going to have to close this.
