### ISSUE TITLE
packet to bytes and back but cannot decode to frameFOO does not build.

### ISSUE THREAD

**Issue by i3587616** [PyAV-Org/PyAV#827]
import av
import av.datasets
input_ = av.open(av.datasets.curated('C:/Users/admin/Downloads/14.mp4'))
input_.streams.video[0].thread_type = 'AUTO'
in_stream = input_.streams.video[0]
in_stream.codec_context.skip_frame = 'NONKEY'
flag = True        
for packet in input_.demux(in_stream): 
    #if packet.is_keyframe:
        #print(packet)
    
    if flag:
        if packet.pts >= 284194800:
            flag = False
            print(packet)
            print(packet.duration)
            print(packet.is_keyframe)
            with open("lastPacket.dat", 'wb') as file_:
                file_.write(packet.to_bytes())
    else :
        print(packet)
        print(packet.duration)
        print(packet.is_keyframe)
        
        with open("lastPacket{}.dat".format(packet.pts), 'wb') as file_:
                file_.write(packet.to_bytes())

this lastPacket.dat save the packet is_keyframe = true

import av
import numpy as np
from fractions import Fraction
codec = av.CodecContext.create('hevc', 'r')
format = av.video.format.VideoFormat('yuv420p')
codec.format = format
codec.height = 3840
codec.width = 2160
codec.rate =25
codec.time_base =  Fraction(1, 90000)

with open("lastPacket.dat", 'rb') as file_:
    buffer = file_.read()
    p = av.packet.Packet(buffer)
    frames = codec.decode(p)
    for frame in frames:
        frame.to_image().save('./temp/{0.index}.{0.pts}.{0.dts}.jpg'.format(frame),quality=30)
No start code is found.
Error splitting the input into NAL units.
Traceback (most recent call last):
  File "hevc_packet.py", line 40, in <module>
    frames = codec.decode(p)
  File "av\codec\context.pyx", line 491, in av.codec.context.CodecContext.decode
  File "av\codec\context.pyx", line 506, in av.codec.context.CodecContext.decode
  File "av\codec\context.pyx", line 409, in av.codec.context.CodecContext._send_packet_and_recv
  File "av\error.pyx", line 336, in av.error.err_check
av.error.InvalidDataError: [Errno 1094995529] Invalid data found when processing input; last error log: [hevc] Error splitting the input into NAL units.

what is wrong

**Comment by i3587616** [comment]
14.mp4 is hevc

**Comment by i3587616** [comment]
<av.Packet of #0, dts=284180400, pts=284194800; 5757 bytes at 0x23ad03e40e0>
3600  packet.duration
True   packet.is_keyframe
<av.Packet of #0, dts=284184000, pts=284202000; 2610 bytes at 0x23ad02d5f40>
3600 packet.duration
False packet.is_keyframe
<av.Packet of #0, dts=284187600, pts=284198400; 375 bytes at 0x23ad03e40e0>
3600 packet.duration
False packet.is_keyframe
<av.Packet of #0, dts=None, pts=None; 0 bytes at 0x23ad02d5f40>

this is the last three packets of the 14.mp4. and the blank frame pts is 284194800.
i want to use the end packets to end video which i generate video.
but i want to see the packet is right the blank frame.
how packet to bytes and back  and decode to frame.

**Comment by i3587616** [comment]
ERROR:libav.hevc:No start code is found.
ERROR:libav.hevc:Error splitting the input into NAL units.

**Comment by i3587616** [comment]
i download the pyav source code .and change output.pyx :
        # Copy from the template.
        if template is not None:
            lib.avcodec_copy_context(codec_context, template._codec_context)
            # Reset the codec tag assuming we are remuxing.
            codec_context.codec_tag = 0
            codec_context.time_base.num = template.time_base.numerator
            codec_context.time_base.den = template.time_base.denominator
            stream.time_base = codec_context.time_base
and then       self.out_stream = self.output.add_stream(template=in_stream)
and 
        with open("lastPacket.dat", 'rb') as file_:
            buffer = file_.read()
            p = av.packet.Packet(buffer)
            p.pts = self.lastPts + 3600
            p.dts = self.lastDts + 3600
            self.output.mux(p)
            print(p.duration)
        with open("lastPacket284202000.dat", 'rb') as file_:
            buffer = file_.read()
            p = av.packet.Packet(buffer)
            p.pts = self.lastPts + 10800
            p.dts = self.lastDts + 7200
            self.output.mux(p)
        with open("lastPacket284198400.dat", 'rb') as file_:
            buffer = file_.read()
            p = av.packet.Packet(buffer)
            p.pts = self.lastPts + 7200
            p.dts = self.lastDts + 10800
            self.output.mux(p)

is good to generate video with i need frames and end with blank frame.
