### ISSUE TITLE
fails test test_reformat_pixel_format_align on PowerPC arches: ALTIVEC: Color Space RGB24

### ISSUE THREAD

**Issue by jonassmedegaard** [PyAV-Org/PyAV#834]
Debian build fails testsuite on hardware architecture ppc64el:
```
=================================== FAILURES ===================================
___________ TestVideoFrameReformat.test_reformat_pixel_format_align ____________

self = <tests.test_videoframe.TestVideoFrameReformat testMethod=test_reformat_pixel_format_align>

    def test_reformat_pixel_format_align(self):
        height = 480
        for width in range(2, 258, 2):
            frame_yuv = VideoFrame(width, height, 'yuv420p')
            for plane in frame_yuv.planes:
                plane.update(b'\xff' * plane.buffer_size)
    
            expected_rgb = numpy.zeros(shape=(height, width, 3), dtype=numpy.uint8)
            expected_rgb[:, :, 0] = 255
            expected_rgb[:, :, 1] = 124
            expected_rgb[:, :, 2] = 255
    
            frame_rgb = frame_yuv.reformat(format='rgb24')
            array_rgb = frame_rgb.to_ndarray()
            self.assertEqual(array_rgb.shape, (height, width, 3))
>           self.assertTrue((array_rgb == expected_rgb).all())
E           AssertionError: False is not true

tests/test_videoframe.py:335: AssertionError
------------------------------ Captured log call -------------------------------
WARNING  libav.swscaler:test_videoframe.py:332 No accelerated colorspace conversion found from yuv420p to rgb24.
WARNING  libav.swscaler:test_videoframe.py:332 No accelerated colorspace conversion found from yuv420p to rgb24.
 (repeated 6 more times)
WARNING  libav.swscaler:test_videoframe.py:332 ALTIVEC: Color Space RGB24
=========================== short test summary info ============================
FAILED tests/test_videoframe.py::TestVideoFrameReformat::test_reformat_pixel_format_align
=========== 1 failed, 112 passed, 8 skipped, 43 deselected in 1.20s ============
```
Full build log: https://buildd.debian.org/status/fetch.php?pkg=python-av&arch=ppc64el&ver=8.0.3-1&stamp=1629295226&raw=0

**Comment by jonassmedegaard** [comment]
Fails same test in seemingly same way for ppc64 (i.e. both bigendian and littleendian 64bit PowerPC): https://buildd.debian.org/status/fetch.php?pkg=python-av&arch=ppc64&ver=8.0.3-3&stamp=1639217021&raw=0

**Comment by jlaine** [comment]
I have a partial reproduction of this, CI fails when I build wheels for ppc64le in #743. However I see two failing tests, not just one:

```
  ======================================================================
  FAIL: test_ndarray_flt (tests.test_audioframe.TestAudioFrameConveniences)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/project/tests/test_audioframe.py", line 132, in test_ndarray_flt
      self.assertTrue((frame.to_ndarray() == array).all())
  AssertionError: False is not true
  
  ======================================================================
  FAIL: test_reformat_pixel_format_align (tests.test_videoframe.TestVideoFrameReformat)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/project/tests/test_videoframe.py", line 345, in test_reformat_pixel_format_align
      self.assertTrue((array_rgb == expected_rgb).all())
  AssertionError: False is not true
  
  ----------------------------------------------------------------------
```

**Comment by jonassmedegaard** [comment]
I don't recognize `test_ndarray_flt` as failing.  The Debian autobuilder for ppc64el succeeds my packaging of v8.1.0 using this command:
```shell
python3.9 -m pytest --ignore=tests/test_doctests.py --ignore=tests/test_timeout.py -k 'not test_audio_transcode and not test_codec_tag and not test_container_probing and not test_context_manager and not test_data and not test_decode_audio_sample_count and not test_decoded_motion_vectors and not test_decoded_time_base and not test_decoded_video_frame_count and not test_decode_half and not test_deprecated_stream_seek and not test_encoding and not test_movtext and not test_parse and not test_reading and not test_seek_end and not test_seek_float and not test_seek_int64 and not test_seek_middle and not test_seek_start and not test_selection and not test_stream_probing and not test_stream_seek and not test_stream_tuples and not test_vobsub and not test_reformat_pixel_format_align' 
```
i.e. a pytest command which excludes `test_reformat_pixel_format_align` and other tests failing only on 32bit bigendian archs, but not `test_ndarray_flt`.

**Comment by jlaine** [comment]
OK, I'm changing the test suite to print out the differences because I really cannot tell what's going on here..

**Comment by jlaine** [comment]
@jonassmedegaard could you possibly let me know the output of these with the latest release (9.0.2)? I'd still expect the test to fail but the failure should be a bit more explicit

**Comment by jonassmedegaard** [comment]
I have not [restructured test routines](https://salsa.debian.org/debian/python-av/-/commit/64f1109) and assuming I did that as intended the [build logs](https://buildd.debian.org/status/package.php?p=python-av) should soon contain also that failing test for PowerPC arches.

**Comment by jonassmedegaard** [comment]
What I mean is that I have restructured test routines *and issued a release based on your v9.0.2* - so no need to dig into current 9.0.1 build logs: Wait for 9.0.2-1 builds to appear.

**Comment by jonassmedegaard** [comment]
Here you go: https://buildd.debian.org/status/fetch.php?pkg=python-av&arch=ppc64el&ver=9.0.2-1&stamp=1648116170&raw=0

**Comment by jonassmedegaard** [comment]
...and here: https://buildd.debian.org/status/fetch.php?pkg=python-av&arch=ppc64&ver=9.0.2-1&stamp=1648116410&raw=0

**Comment by jonassmedegaard** [comment]
Oh, it seems 32bit PowerPC also fails: https://buildd.debian.org/status/fetch.php?pkg=python-av&arch=powerpc&ver=9.0.2-1&stamp=1648116381&raw=0

**Comment by jonassmedegaard** [comment]
Perhaps 32bit PowerPC was missed earlier due to some build daemons tolerating Altivec operations - unless it was you changing the tests to now fail more generally.

**Comment by jlaine** [comment]
I am not convinced this is a bug in PyAV, there seems to be a history of format conversion issues with PPC:

https://trac.ffmpeg.org/ticket/7124

**Comment by jlaine** [comment]
@jonassmedegaard sorry I think the stale bot settings are a bit too agressive..

**Comment by jonassmedegaard** [comment]
Quoting github-actions[bot] (2023-02-16 03:37:06)
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

Bot too aggressive again?
